### ISSUE TITLE
How to bulid our new datasets of doc_id.txt?

### ISSUE THREAD

**Issue by WindHunter-Yang** [yumeng5/WeSTClass#2]
In  doc_id.txt, how to select our datasets' doc_id, I don't kown how to bulid, what does the doc_id refer to ? Can you help me? Please

**Comment by yumeng5** [comment]
Hi,

The doc_id.txt file contains the supervision sources in the form of labeled documents. (See the Inputs section of the README file for details) Therefore, you will need to provide this file by manually labeling some documents on your own. For example, in agnews/doc_id.txt, I manually chose 10 documents per class as the supervision source. You can definitely provide different labelings as document-level supervision. 

Note that if you are using label surface names or class-related keywords as supervision, you do not need to provide the doc_id.txt file at all. 

Please let me know if you have further questions.

Thanks,
Yu
